apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: customer-app
build:
  artifacts:
    - image: customer-app
      context: .
      docker:
        dockerfile: app/Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - k8s/postgres.yaml
    - k8s/app.yaml
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: customer-service
    port: 80
    localPort: 8080