apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app
spec:
  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: [ 'sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done' ]
      containers:
        - name: customer-app
          image: customer-app
          ports:
            - containerPort: 8080
          env:
            - name: JDBC_URL
              value: jdbc:postgresql://postgres:5432/customerdb
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
